import { getLocalDateString } from './utils';

export interface CategoryData {
  id: string;
  name: string;
  emoji: string;
  tint: string;
  type: 'expense' | 'income';
}

export interface TransactionData {
  id: string;
  listId: string;
  description: string;
  amount: number;
  type: 'expense' | 'income';
  categoryId: string;
  tags: string[];
  date: string; // ISO String YYYY-MM-DD in America/Bogota
  recurrence: 'once' | 'daily' | 'weekly' | 'biweekly' | 'monthly' | 'bimonthly' | 'quarterly' | 'yearly';
  createdAt: string;
}

export interface SubscriptionData {
  id: string;
  listId: string;
  name: string;
  emoji: string;
  amount: number;
  frequency: 'monthly' | 'weekly' | 'bimonthly' | 'yearly';
  billingDay: number;
  categoryId: string;
  tags: string[];
  lastPaidDate?: string;
  createdAt: string;
  provider?: string;
  cancelUrl?: string;
  cancelSteps?: string;
  notes?: string;
  trialEndDate?: string | null;
  flaggedLowUsage?: boolean;
  status?: 'ACTIVE' | 'TRIAL' | 'TO_CANCEL' | 'VERIFIED_CANCELLED';
}

export interface ListData {
  id: string;
  name: string;
  currency: string;
  defaultPeriod: string;
}

export interface BudgetData {
  id: string;
  listId: string;
  categoryId: string;
  monthlyAmount: number;
}

export const INITIAL_LISTS: ListData[] = [
  { id: 'list-1', name: 'RappiPay', currency: 'COP', defaultPeriod: 'Month' },
  { id: 'list-2', name: 'Personal', currency: 'COP', defaultPeriod: 'Month' },
];

export const INITIAL_CATEGORIES: CategoryData[] = [
  { id: 'cat-1', name: 'Mamá', emoji: '👩‍🍼', tint: '#8A7A55', type: 'expense' },
  { id: 'cat-2', name: 'Papá', emoji: '👴', tint: '#A8862B', type: 'income' },
  { id: 'cat-3', name: 'Gym', emoji: '🏋️', tint: '#7A5C43', type: 'expense' },
  { id: 'cat-4', name: 'Comida', emoji: '🍲', tint: '#8A6E4B', type: 'expense' },
  { id: 'cat-5', name: 'Uber', emoji: '🚘', tint: '#A05252', type: 'expense' },
  { id: 'cat-6', name: 'Suscripción', emoji: '📺', tint: '#5B6A8A', type: 'expense' },
  { id: 'cat-7', name: 'Apple', emoji: '🖥️', tint: '#707075', type: 'expense' },
  { id: 'cat-8', name: 'Apuestas', emoji: '🎲', tint: '#8A5B7A', type: 'expense' },
  { id: 'cat-9', name: 'Barbero', emoji: '💈', tint: '#5B8A82', type: 'expense' },
  { id: 'cat-10', name: 'Drinks', emoji: '🍺', tint: '#8A845B', type: 'expense' },
  { id: 'cat-11', name: 'Regalo', emoji: '🎁', tint: '#8A5B5B', type: 'expense' },
  { id: 'cat-12', name: 'Amorcito', emoji: '💙', tint: '#5B7A8A', type: 'expense' },
  { id: 'cat-13', name: 'Personal', emoji: '🧍', tint: '#6A5B8A', type: 'expense' },
  { id: 'cat-14', name: 'Salidas', emoji: '🎉', tint: '#8A5B7A', type: 'expense' },
  { id: 'cat-15', name: 'Credito', emoji: '💳', tint: '#34C759', type: 'income' },
];

export const INITIAL_TAGS: string[] = [
  '#debito', '#credito', '#mama', '#papa', '#gym', '#almuerzo',
  '#icloud+', '#suscripción', '#carrro', '#movistar', '#apple', '#netflix', '#chatgpt', '#yo', '#miniña', '#cine', '#monai', '#applemusic', '#cash'
];

export const INITIAL_SUBSCRIPTIONS: SubscriptionData[] = [
  {
    id: 'sub-1',
    listId: 'list-1',
    name: 'iCloud+',
    emoji: '☁️',
    amount: 44900,
    frequency: 'monthly',
    billingDay: 3,
    categoryId: 'cat-6',
    tags: ['#icloud+', '#credito'],
    lastPaidDate: '2026-08-03',
    provider: 'Apple',
    cancelUrl: 'https://support.apple.com/subscriptions',
    cancelSteps: 'Ajustes de iOS -> iCloud -> Gestionar almacenamiento',
    notes: '200GB almacenamiento familiar',
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sub-2',
    listId: 'list-1',
    name: 'WhatsApp plus',
    emoji: '💬',
    amount: 2999,
    frequency: 'monthly',
    billingDay: 3,
    categoryId: 'cat-6',
    tags: ['#suscripción', '#credito'],
    lastPaidDate: '2026-08-03',
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sub-3',
    listId: 'list-1',
    name: 'Bodyfit Fitness Center',
    emoji: '🏋️',
    amount: 105000,
    frequency: 'monthly',
    billingDay: 7,
    categoryId: 'cat-3',
    tags: ['#debito', '#gym'],
    lastPaidDate: '2026-08-05',
    provider: 'Bodyfit',
    notes: 'Gimnasio principal',
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sub-4',
    listId: 'list-1',
    name: 'Datos mamá',
    emoji: '📱',
    amount: 35000,
    frequency: 'monthly',
    billingDay: 1,
    categoryId: 'cat-1',
    tags: ['#debito', '#movistar', '#mama'],
    provider: 'Movistar',
    cancelUrl: 'https://www.movistar.co',
    cancelSteps: 'Llamar al servicio al cliente o ingresar a Mi Movistar',
    notes: 'Plan móvil familiar',
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sub-5',
    listId: 'list-1',
    name: 'Apple Music',
    emoji: '🎵',
    amount: 8500,
    frequency: 'monthly',
    billingDay: 15,
    categoryId: 'cat-7',
    tags: ['#credito', '#apple'],
    provider: 'Apple',
    cancelUrl: 'https://support.apple.com/subscriptions',
    cancelSteps: 'Ajustes de iOS -> Apple ID -> Suscripciones',
    notes: 'Música en alta definición',
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sub-6',
    listId: 'list-1',
    name: 'Netflix Premium',
    emoji: '🍿',
    amount: 44900,
    frequency: 'monthly',
    billingDay: 12,
    categoryId: 'cat-6',
    tags: ['#credito', '#netflix'],
    provider: 'Netflix',
    cancelUrl: 'https://www.netflix.com/youraccount',
    cancelSteps: 'Cuenta -> Cancelar membresía',
    notes: 'Plan 4K UHD',
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sub-7',
    listId: 'list-1',
    name: 'ChatGPT Plus',
    emoji: '🤖',
    amount: 84000,
    frequency: 'monthly',
    billingDay: 18,
    categoryId: 'cat-6',
    tags: ['#credito', '#chatgpt'],
    provider: 'OpenAI',
    cancelUrl: 'https://chatgpt.com',
    cancelSteps: 'My Account -> Manage Subscription',
    notes: 'Acceso GPT-4o',
    status: 'ACTIVE',
    flaggedLowUsage: false,
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_TRANSACTIONS: TransactionData[] = [
  // AUGUST 11, 2026 (-$30,400 Expense, +$65,362 Income)
  {
    id: 'tx-aug11-1',
    listId: 'list-1',
    description: 'Salchipapa',
    amount: 26000,
    type: 'expense',
    categoryId: 'cat-4',
    tags: ['#debito'],
    date: '2026-08-11',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-aug11-2',
    listId: 'list-1',
    description: 'Pandebonos',
    amount: 4400,
    type: 'expense',
    categoryId: 'cat-4',
    tags: ['#debito'],
    date: '2026-08-11',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-aug11-3',
    listId: 'list-1',
    description: 'Rembolso',
    amount: 11362,
    type: 'income',
    categoryId: 'cat-15',
    tags: ['#credito'],
    date: '2026-08-11',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-aug11-4',
    listId: 'list-1',
    description: 'Ingreso Papa',
    amount: 30000,
    type: 'income',
    categoryId: 'cat-2',
    tags: ['#papa', '#debito'],
    date: '2026-08-11',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-aug11-5',
    listId: 'list-1',
    description: 'Ingreso',
    amount: 24000,
    type: 'income',
    categoryId: 'cat-13',
    tags: ['#debito'],
    date: '2026-08-11',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },

  // AUGUST 10, 2026 (-$8,500 Expense, +$60,000 Income)
  {
    id: 'tx-aug10-1',
    listId: 'list-1',
    description: 'Apple Music',
    amount: 8500,
    type: 'expense',
    categoryId: 'cat-6',
    tags: ['#applemusic', '#credito'],
    date: '2026-08-10',
    recurrence: 'monthly',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-aug10-2',
    listId: 'list-1',
    description: 'Papá',
    amount: 60000,
    type: 'income',
    categoryId: 'cat-2',
    tags: ['#papa', '#cash'],
    date: '2026-08-10',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },

  // AUGUST 9, 2026 (-$124,464 Expense, +$30,000 Income)
  {
    id: 'tx-aug9-1',
    listId: 'list-1',
    description: 'MonAI',
    amount: 14900,
    type: 'expense',
    categoryId: 'cat-6',
    tags: ['#credito', '#monai'],
    date: '2026-08-09',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-aug9-2',
    listId: 'list-1',
    description: 'Almuerzo arroz montañero',
    amount: 20000,
    type: 'expense',
    categoryId: 'cat-4',
    tags: ['#debito', '#almuerzo'],
    date: '2026-08-09',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-aug9-3',
    listId: 'list-1',
    description: 'pandebonos',
    amount: 10000,
    type: 'expense',
    categoryId: 'cat-4',
    tags: ['#debito'],
    date: '2026-08-09',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-aug9-4',
    listId: 'list-1',
    description: 'Uber',
    amount: 33564,
    type: 'expense',
    categoryId: 'cat-5',
    tags: ['#debito'],
    date: '2026-08-09',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-aug9-5',
    listId: 'list-1',
    description: 'Salchipapa',
    amount: 46000,
    type: 'expense',
    categoryId: 'cat-4',
    tags: ['#debito'],
    date: '2026-08-09',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-aug9-6',
    listId: 'list-1',
    description: 'Dinero recibido de mi niña',
    amount: 30000,
    type: 'income',
    categoryId: 'cat-12',
    tags: ['#debito', '#miniña'],
    date: '2026-08-09',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },

  // AUGUST 8, 2026 (-$86,432 Expense)
  {
    id: 'tx-aug8-1',
    listId: 'list-1',
    description: 'Uber',
    amount: 5380,
    type: 'expense',
    categoryId: 'cat-5',
    tags: ['#debito', '#yo', '#carrro'],
    date: '2026-08-08',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-aug8-2',
    listId: 'list-1',
    description: 'Uber',
    amount: 6821,
    type: 'expense',
    categoryId: 'cat-5',
    tags: ['#debito', '#yo'],
    date: '2026-08-08',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-aug8-3',
    listId: 'list-1',
    description: 'Uber',
    amount: 32002,
    type: 'expense',
    categoryId: 'cat-5',
    tags: ['#debito', '#yo', '#carrro'],
    date: '2026-08-08',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-aug8-4',
    listId: 'list-1',
    description: 'Entradas cine',
    amount: 23200,
    type: 'expense',
    categoryId: 'cat-14',
    tags: ['#debito', '#cine'],
    date: '2026-08-08',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-aug8-5',
    listId: 'list-1',
    description: 'Ajuste',
    amount: 19029,
    type: 'expense',
    categoryId: 'cat-2',
    tags: ['#debito'],
    date: '2026-08-08',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },

  // AUGUST 7, 2026 (-$77,400 Expense, +$25,326 Income)
  {
    id: 'tx-aug7-1',
    listId: 'list-1',
    description: 'Juego para mi niña',
    amount: 3500,
    type: 'expense',
    categoryId: 'cat-12',
    tags: ['#debito', '#miniña'],
    date: '2026-08-07',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-aug7-2',
    listId: 'list-1',
    description: 'Apple',
    amount: 16500,
    type: 'expense',
    categoryId: 'cat-7',
    tags: ['#debito', '#apple-pay'],
    date: '2026-08-07',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-aug7-3',
    listId: 'list-1',
    description: 'Apple',
    amount: 18400,
    type: 'expense',
    categoryId: 'cat-7',
    tags: ['#credito'],
    date: '2026-08-07',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-aug7-4',
    listId: 'list-1',
    description: 'Arroz montañero',
    amount: 39000,
    type: 'expense',
    categoryId: 'cat-4',
    tags: ['#debito', '#almuerzo'],
    date: '2026-08-07',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-aug7-5',
    listId: 'list-1',
    description: 'Ajuste',
    amount: 5326,
    type: 'income',
    categoryId: 'cat-2',
    tags: ['#debito'],
    date: '2026-08-07',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-aug7-6',
    listId: 'list-1',
    description: 'Dinero recibido de primo',
    amount: 20000,
    type: 'income',
    categoryId: 'cat-13',
    tags: ['#debito'],
    date: '2026-08-07',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },

  // AUGUST 6, 2026 (-$6,471 Expense)
  {
    id: 'tx-aug6-1',
    listId: 'list-1',
    description: 'Uber mi niña',
    amount: 6471,
    type: 'expense',
    categoryId: 'cat-5',
    tags: ['#debito', '#miniña'],
    date: '2026-08-06',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },

  // AUGUST 5, 2026 (-$412,776 Expense, +$3,253,961 Income)
  {
    id: 'tx-1',
    listId: 'list-1',
    description: 'Bodyfit Fitness Center',
    amount: 105000,
    type: 'expense',
    categoryId: 'cat-3',
    tags: ['#debito', '#gym'],
    date: '2026-08-05',
    recurrence: 'monthly',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-2',
    listId: 'list-1',
    description: 'Mamá fallabella',
    amount: 182400,
    type: 'expense',
    categoryId: 'cat-1',
    tags: ['#credito', '#mama'],
    date: '2026-08-05',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-3',
    listId: 'list-1',
    description: 'Mamá',
    amount: 6000,
    type: 'expense',
    categoryId: 'cat-1',
    tags: ['#debito', '#mama'],
    date: '2026-08-05',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-4',
    listId: 'list-1',
    description: 'Uber',
    amount: 6226,
    type: 'expense',
    categoryId: 'cat-5',
    tags: ['#debito', '#mama'],
    date: '2026-08-05',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-5',
    listId: 'list-1',
    description: 'Qbano',
    amount: 48150,
    type: 'expense',
    categoryId: 'cat-4',
    tags: ['#credito', '#almuerzo'],
    date: '2026-08-05',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-9',
    listId: 'list-1',
    description: 'Arepas',
    amount: 65000,
    type: 'expense',
    categoryId: 'cat-4',
    tags: ['#debito'],
    date: '2026-08-05',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },

  {
    id: 'tx-6',
    listId: 'list-1',
    description: 'Dinero recibido de papá',
    amount: 200000,
    type: 'income',
    categoryId: 'cat-2',
    tags: ['#debito', '#papa'],
    date: '2026-08-05',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-7',
    listId: 'list-1',
    description: 'Dinero recibido de papá',
    amount: 100000,
    type: 'income',
    categoryId: 'cat-2',
    tags: ['#debito', '#papa'],
    date: '2026-08-05',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-8',
    listId: 'list-1',
    description: 'Ajuste',
    amount: 13797,
    type: 'income',
    categoryId: 'cat-2',
    tags: ['#papa'],
    date: '2026-08-05',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-10',
    listId: 'list-1',
    description: 'Papá',
    amount: 70000,
    type: 'income',
    categoryId: 'cat-2',
    tags: ['#debito', '#papa'],
    date: '2026-08-05',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-11',
    listId: 'list-1',
    description: 'Crédito',
    amount: 2700000,
    type: 'income',
    categoryId: 'cat-15',
    tags: ['#credito'],
    date: '2026-08-05',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-12',
    listId: 'list-1',
    description: 'Ajuste',
    amount: 170164,
    type: 'income',
    categoryId: 'cat-2',
    tags: ['#debito', '#papa'],
    date: '2026-08-05',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },

  // AUGUST 4, 2026 (-$32,964 Expense)
  {
    id: 'tx-13',
    listId: 'list-1',
    description: 'Mercar bochalema',
    amount: 32964,
    type: 'expense',
    categoryId: 'cat-4',
    tags: ['#debito'],
    date: '2026-08-04',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },

  // AUGUST 3, 2026 (-$298,230 Expense, +$147,000 Income)
  {
    id: 'tx-14',
    listId: 'list-1',
    description: 'iCloud+',
    amount: 44900,
    type: 'expense',
    categoryId: 'cat-6',
    tags: ['#icloud+', '#credito'],
    date: '2026-08-03',
    recurrence: 'monthly',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-15',
    listId: 'list-1',
    description: 'Mamá',
    amount: 247158,
    type: 'expense',
    categoryId: 'cat-1',
    tags: ['#credito', '#mama'],
    date: '2026-08-03',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-16',
    listId: 'list-1',
    description: 'WhatsApp plus',
    amount: 2999,
    type: 'expense',
    categoryId: 'cat-6',
    tags: ['#suscripción', '#credito'],
    date: '2026-08-03',
    recurrence: 'monthly',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-17',
    listId: 'list-1',
    description: 'Uber',
    amount: 3173,
    type: 'expense',
    categoryId: 'cat-5',
    tags: ['#debito', '#carrro'],
    date: '2026-08-03',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-18',
    listId: 'list-1',
    description: 'Papá',
    amount: 147000,
    type: 'income',
    categoryId: 'cat-2',
    tags: ['#debito', '#papa'],
    date: '2026-08-03',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },

  // AUGUST 2, 2026 (-$359,128 Expense)
  {
    id: 'tx-19',
    listId: 'list-1',
    description: 'Uber',
    amount: 22977,
    type: 'expense',
    categoryId: 'cat-5',
    tags: ['#carrro', '#credito'],
    date: '2026-08-02',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-20',
    listId: 'list-1',
    description: 'Uber',
    amount: 27251,
    type: 'expense',
    categoryId: 'cat-5',
    tags: ['#carrro', '#credito'],
    date: '2026-08-02',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-21',
    listId: 'list-1',
    description: 'Avance',
    amount: 200000,
    type: 'expense',
    categoryId: 'cat-15',
    tags: ['#credito'],
    date: '2026-08-02',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-22',
    listId: 'list-1',
    description: 'Dollarcity',
    amount: 12500,
    type: 'expense',
    categoryId: 'cat-13',
    tags: ['#debito'],
    date: '2026-08-02',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-23',
    listId: 'list-1',
    description: 'KFC',
    amount: 36400,
    type: 'expense',
    categoryId: 'cat-4',
    tags: ['#debito', '#almuerzo'],
    date: '2026-08-02',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-24',
    listId: 'list-1',
    description: 'Entradas fiesta',
    amount: 60000,
    type: 'expense',
    categoryId: 'cat-14',
    tags: ['#debito'],
    date: '2026-08-02',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },

  // AUGUST 1, 2026 (-$1,456,125 Expense)
  {
    id: 'tx-25',
    listId: 'list-1',
    description: 'Mamá rodilleras',
    amount: 71155,
    type: 'expense',
    categoryId: 'cat-1',
    tags: ['#credito', '#mama'],
    date: '2026-08-01',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-26',
    listId: 'list-1',
    description: 'Mamá pull and bear',
    amount: 240500,
    type: 'expense',
    categoryId: 'cat-1',
    tags: ['#credito', '#mama'],
    date: '2026-08-01',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-27',
    listId: 'list-1',
    description: 'Mamá Zara',
    amount: 370800,
    type: 'expense',
    categoryId: 'cat-1',
    tags: ['#credito', '#mama'],
    date: '2026-08-01',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-28',
    listId: 'list-1',
    description: 'Crédito',
    amount: 417283,
    type: 'expense',
    categoryId: 'cat-15',
    tags: ['#credito'],
    date: '2026-08-01',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-29',
    listId: 'list-1',
    description: 'Mamá ropa',
    amount: 119900,
    type: 'expense',
    categoryId: 'cat-1',
    tags: ['#credito', '#mama'],
    date: '2026-08-01',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-30',
    listId: 'list-1',
    description: 'Uber',
    amount: 30261,
    type: 'expense',
    categoryId: 'cat-5',
    tags: ['#carrro', '#credito'],
    date: '2026-08-01',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-31',
    listId: 'list-1',
    description: 'Mamá ropa',
    amount: 132480,
    type: 'expense',
    categoryId: 'cat-1',
    tags: ['#credito', '#mama'],
    date: '2026-08-01',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-32',
    listId: 'list-1',
    description: 'Uber',
    amount: 34487,
    type: 'expense',
    categoryId: 'cat-5',
    tags: ['#carrro', '#credito'],
    date: '2026-08-01',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-33',
    listId: 'list-1',
    description: 'Uber',
    amount: 10599,
    type: 'expense',
    categoryId: 'cat-5',
    tags: ['#debito', '#carrro'],
    date: '2026-08-01',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-34',
    listId: 'list-1',
    description: 'Uber',
    amount: 3660,
    type: 'expense',
    categoryId: 'cat-5',
    tags: ['#debito', '#carrro'],
    date: '2026-08-01',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-35',
    listId: 'list-1',
    description: 'Cóctel',
    amount: 25000,
    type: 'expense',
    categoryId: 'cat-10',
    tags: ['#debito'],
    date: '2026-08-01',
    recurrence: 'once',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_BUDGETS: BudgetData[] = [
  { id: 'b-1', listId: 'list-1', categoryId: 'cat-3', monthlyAmount: 200000 },
  { id: 'b-2', listId: 'list-1', categoryId: 'cat-4', monthlyAmount: 300000 },
  { id: 'b-3', listId: 'list-1', categoryId: 'cat-1', monthlyAmount: 1500000 },
];
